version: "3.1"

services:
  db:
    build: .
    container_name: marmota
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nesttrainer

  dbtest:
    build: .
    container_name: marmota-teste
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nesttrainer